import { registerEnumType } from '@nestjs/graphql/dist';

export enum TriggerEvent {
  SUBMISSION_EVALUATED = 'SUBMISSION EVALUATED',
  SUBMISSION_RECEIVED = 'SUBMISSION RECEIVED',
  SUBMISSION_ACCEPTED = 'SUBMISSION ACCEPTED',
  SUBMISSION_REJECTED = 'SUBMISSION REJECTED',
  CHALLENGE_COMPLETED = 'CHALLENGE COMPLETED',
  CHALLENGE_FAILED = 'CHALLENGE FAILED',
  REWARD_GRANTED = 'REWARD GRANTED',
  PLAYER_UPDATED = 'PLAYER UPDATED',
  POINTS_UPDATED = 'POINTS UPDATED',
  DUEL_INVITATION_RECEIVED = 'DUEL INVITATION RECEIVED',
  DUEL_INITIATED = 'DUEL INITIATED',
  DUEL_ACCEPTED = 'DUEL ACCEPTED',
  DUEL_REJECTED = 'DUEL REJECTED',
  DUEL_COMPLETED = 'DUEL COMPLETED',
}

registerEnumType(TriggerEvent, { name: 'TriggerEvent' });
