version: "3.7"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - PORT=${APP_PORT}
        - NODE_ENV=${NODE_ENV}
    user: node
    working_dir: /home/node/app
    env_file:
      - ./.env
    volumes:
      - ./src:/home/node/app/src
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mongodb
      - redis
      - mooshak-mock
    networks:
      - fgpe-gs-nw
    command: "npm run start:dev"

  mongodb:
    container_name: ${DB_HOST}
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      #- ./docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - fgpe-gs-db:/data/db
    networks:
      - fgpe-gs-nw

  redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - fgpe-gs-redis:/data/redis
    networks:
      - fgpe-gs-nw

  mooshak-mock:
    container_name: ${EE_HOST}
    image: jcpaiva/mooshak-fgpe
    volumes:
      - fgpe-gs-mooshak-mock:/home/mooshak/data
    networks:
      - fgpe-gs-nw

volumes:
  fgpe-gs-db: {}
  fgpe-gs-redis: {}
  fgpe-gs-mooshak-mock: {}

networks:
  fgpe-gs-nw:
