import { registerEnumType } from '@nestjs/graphql/dist';

export enum TriggerEventEnum {
  SUBMISSION_EVALUATED = 'SUBMISSION_EVALUATED',
  SUBMISSION_RECEIVED = 'SUBMISSION_RECEIVED',
  SUBMISSION_ACCEPTED = 'SUBMISSION_ACCEPTED',
  SUBMISSION_REJECTED = 'SUBMISSION_REJECTED',
  CHALLENGE_COMPLETED = 'CHALLENGE_COMPLETED',
  CHALLENGE_FAILED = 'CHALLENGE_FAILED',
  REWARD_GRANTED = 'REWARD_GRANTED',
  PLAYER_UPDATED = 'PLAYER_UPDATED',
  POINTS_UPDATED = 'POINTS_UPDATED',
  DUEL_INVITATION_RECEIVED = 'DUEL_INVITATION_RECEIVED',
  DUEL_INITIATED = 'DUEL_INITIATED',
  DUEL_ACCEPTED = 'DUEL_ACCEPTED',
  DUEL_REJECTED = 'DUEL_REJECTED',
  DUEL_COMPLETED = 'DUEL_COMPLETED',
}

registerEnumType(TriggerEventEnum, { name: 'TriggerEvent' });
