# build stage
FROM node:lts-alpine as builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm set unsafe-perm true
RUN npm install

COPY . .

RUN npm run build

# production stage
FROM node:lts-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm set unsafe-perm true
RUN npm install --only=production

COPY --from=builder /usr/src/app/dist ./dist

CMD ["node", "dist/src/main"]
