import { registerEnumType } from '@nestjs/graphql';

export enum NotificationEnum {
  REWARD_RECEIVED = 'REWARD_RECEIVED',
  REWARD_SUBSTRACTED = 'REWARD_SUBSTRACTED',
  REWARD_REMOVED = 'REWARD_REMOVED',
  POINTS_UPDATED = 'POINTS_UPDATED',
  PLAYER_ENROLLED = 'PLAYER_ENROLLED',
  PLAYER_LEFT = 'PLAYER_LEFT',
  CHALLENGE_STATUS_UPDATED = 'CHALLENGE_STATUS_UPDATED',
  SUBMISSION_SENT = 'SUBMISSION_SENT',
  SUBMISSION_EVALUATED = 'SUBMISSION_EVALUATED',
  VALIDATION_PROCESSED = 'VALIDATION_PROCESSED',
  GAME_STARTED = 'GAME_STARTED',
  GAME_FINISHED = 'GAME_FINISHED',
  GAME_MODIFIED = 'GAME_MODIFIED',
  CHALLENGE_MODIFIED = 'CHALLENGE_MODIFIED',
  LEADERBOARD_MODIFIED = 'LEADERBOARD_MODIFIED',
  REWARD_MODIFIED = 'REWARD_MODIFIED',
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
}

registerEnumType(NotificationEnum, { name: 'NotificationEnum' });
