import { registerEnumType } from '@nestjs/graphql';

export enum NotificationEnum {
  REWARD_RECEIVED = 'REWARD-RECEIVED',
  SUBMISSION_UPDATED = 'SUBMISSION_UPDATED',
  CHALLENGE_STATUS_UPDATED = 'CHALLENGE_STATUS_UPDATED',
  POINTS_UPDATED = 'POINTS_UPDATED',
  REWARD_SUBSTRACTED = 'REWARD_SUBSTRACTED',
  REWARD_REMOVED = 'REWARD_REMOVED',
  PLAYER_ENROLLED = 'PLAYER_ENROLLED',
  SUBMISSION_SENT = 'SUBMISSION_SENT',
  SUBMISSION_EVALUATED = 'SUBMISSION_EVALUATED',
}

registerEnumType(NotificationEnum, { name: 'NotificationEnum' });
